[theme]
base = "light"
primaryColor = "#01696f"
backgroundColor = "#f7f6f2"
secondaryBackgroundColor = "#f3f0ec"
textColor = "#28251d"
font = "sans serif"

[server]
headless = true
address = "localhost"
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
